Modern cicd - manually merged (#59)
* copied onboard-app from other branch to avoid merge madness

* add onboard.sh based off deploy.sh

* bump tf

* update ref

* drop refs

* bump google provider

* fix auto replication block in latest provider

* drop old refs

* oof

* move SLOs tf into app-repo

* fix slo state location

* chmod

* fixes from end-to-end

* there is another

* slashes not needed

* update licenses

* moar licenses

* drop old yamls - not used

* remove SLO creation as it's currently broken.

* delete unused outputs comments

* docs!

* update top README also

* more

* Revert "drop old yamls - not used"

This reverts commit 191d1a0c7f70c846f756f75f3770bce0ee16f649.

* make it work for now

* fix: update config-management to supported version

deployment error:

Error: Error creating FeatureMembership: googleapi: Error 400: InvalidValueError for field version: unsupported ACM version 1.15.1 for Membership projects/<redacted>/locations/global/memberships/config-us-central1, supported versions are 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.18.0
│

---------

Co-authored-by: Marc Dougherty <muncus@users.noreply.github.com>